### ISSUE TITLE
CFN template fails in China regions

### ISSUE THREAD

**Issue by Chen188** [Netflix/metaflow-tools#16]
**Issue desc:**
1. apigw in China regions do not support Edge-optimized endpoint configuration, which will cause error `Endpoint Configuration type EDGE is not supported in this region: cn-northeast-1`
2. for new AWS account in China regions, the default allowed notebook instance types are ml.t2.medium and ml.t3.medium, thus this template will failed due to notebook instance limitation. 

**solution:**
1. specify the EndpointConfiguration under Api / Properties section:

```
  Api:
    DependsOn: VpcLink
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      EndpointConfiguration:
        Types:
        - REGIONAL
```
2. update instance types:

```
Parameters:
  SagemakerInstance: 
    Type: String
    Default: ml.t3.medium
    AllowedValues: ['ml.t3.medium','ml.t2.medium']
    Description: 'Instance type for Sagemaker Notebook.'
```
